spring.application.name=workbridge

spring.datasource.url=jdbc:postgresql://localhost:5432/workbridge
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true