spring.application.name=workbridge

# Render PORT binding
server.port=${PORT}

# PostgreSQL (Render ENV variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# File upload
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB